# Generated by Django 5.0.6 on 2026-01-17 17:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField(blank=True, verbose_name='Квалификация и сертификаты')),
                ('specialization', models.CharField(blank=True, help_text='Например: начинающие, продвинутые, дети, взрослые', max_length=200, verbose_name='Специализация')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Часовая ставка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации как тренер')),
                ('coach_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг тренера')),
                ('contact_info', models.JSONField(blank=True, default=dict, verbose_name='Контактная информация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Профиль тренера',
                'verbose_name_plural': 'Профили тренеров',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('registration', 'Регистрация'), ('phone_verification', 'Подтверждение телефона'), ('booking_created', 'Бронирование создано'), ('booking_confirmed', 'Бронирование подтверждено'), ('booking_cancelled', 'Бронирование отменено'), ('booking_reminder_24h', 'Напоминание за 24 часа'), ('booking_reminder_1h', 'Напоминание за 1 час'), ('payment_success', 'Оплата успешна'), ('payment_failed', 'Ошибка оплаты'), ('payment_pending', 'Ожидает оплаты'), ('rating_updated', 'Рейтинг обновлен'), ('booking_invitation', 'Приглашение в бронирование'), ('invitation_accepted', 'Приглашение принято'), ('invitation_declined', 'Приглашение отклонено'), ('partner_joined', 'Партнёр присоединился')], db_index=True, max_length=50, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email отправлен')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS отправлено')),
                ('push_sent', models.BooleanField(default=False, verbose_name='Push отправлено')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx'), models.Index(fields=['type'], name='users_notif_type_0792c9_idx'), models.Index(fields=['created_at'], name='users_notif_created_3ee999_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerCoachRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная связь')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Связь игрок-тренер',
                'verbose_name_plural': 'Связи игрок-тренер',
                'unique_together': {('player', 'coach')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_rating', models.DecimalField(decimal_places=2, default=1.0, help_text='Значение от 1.00 до 7.00', max_digits=3, verbose_name='Числовой рейтинг')),
                ('level', models.CharField(choices=[('D', 'Уровень 1 (D): Новичок'), ('D+', 'Уровень 1+ (D+): Начинающий'), ('C-', 'Уровень 2 (C-): Начинающий / Слабый средний'), ('C', 'Уровень 2+ (C): Средний'), ('C+', 'Уровень 3 (C+): Средний / Крепкий любитель'), ('B-', 'Уровень 3+ (B-): Крепкий любитель'), ('B', 'Уровень 4 (B): Продвинутый'), ('B+', 'Уровень 4+ (B+): Топ-любитель'), ('A', 'Уровень 5/5+ (A): Кандидат/Мастер спорта'), ('PRO', 'Уровень 6-7 (Pro): Профессионал')], default='D', editable=False, max_length=10, verbose_name='Уровень')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('coach_comment', models.TextField(blank=True, verbose_name='Комментарий тренера')),
                ('rating_history', models.JSONField(blank=True, default=list, verbose_name='История рейтинга')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Рейтинг игрока',
                'verbose_name_plural': 'Рейтинги игроков',
                'ordering': ['-numeric_rating'],
                'indexes': [models.Index(fields=['user', 'updated_at'], name='users_playe_user_id_9dd3d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки тренера')),
                ('player_feedback', models.TextField(blank=True, verbose_name='Отзыв игрока')),
                ('rating_given', models.BooleanField(default=False, verbose_name='Рейтинг обновлен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.court', verbose_name='Корт')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Тренировочная сессия',
                'verbose_name_plural': 'Тренировочные сессии',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['coach', 'date'], name='users_train_coach_i_808f2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79123456789'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Телефон подтвержден')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения телефона')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('email_verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения email')),
                ('email_pending', models.EmailField(blank=True, help_text='Новый email, ожидающий подтверждения', max_length=254, null=True, verbose_name='Email в ожидании подтверждения')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Предпочтения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['phone'], name='users_userp_phone_ed0c08_idx'), models.Index(fields=['phone', 'user'], name='users_userp_phone_53f624_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('phone',), name='unique_userprofile_phone'),
        ),
    ]
