# Generated by Django 5.0.6 on 2026-01-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_available'], name='booking_cou_is_avai_5a117a_idx'), models.Index(fields=['name'], name='booking_cou_name_40796a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[('game', 'Игра'), ('training', 'Тренировка')], db_index=True, default='game', help_text='Игра или тренировка', max_length=20, verbose_name='Тип бронирования')),
                ('looking_for_partner', models.BooleanField(default=False, verbose_name='Ищет партнёра')),
                ('max_players', models.IntegerField(default=4, help_text='Максимальное количество игроков (включая создателя)', verbose_name='Макс. игроков')),
                ('required_rating_level', models.CharField(blank=True, help_text='Буквенный рейтинг для поиска партнёров (например: C+, B-)', max_length=10, null=True, verbose_name='Требуемый уровень игры')),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Тренеры'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_as_coach', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('partners', models.ManyToManyField(blank=True, related_name='bookings_as_partner', to=settings.AUTH_USER_MODEL, verbose_name='Партнёры')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_created', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.court')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('refunded', 'Возвращено'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('cash', 'Наличные'), ('online', 'Онлайн оплата')], default='online', max_length=20, verbose_name='Способ оплаты')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='ID транзакции')),
                ('payment_intent_id', models.CharField(blank=True, help_text='Используется для интеграции с платежными системами', max_length=255, null=True, verbose_name='ID платежного намерения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Для хранения данных платежной системы', verbose_name='Дополнительные данные')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создано'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('payment_pending', 'Ожидает оплаты'), ('payment_paid', 'Оплачено'), ('payment_refunded', 'Оплата возвращена'), ('payment_failed', 'Ошибка оплаты'), ('modified', 'Изменено')], db_index=True, max_length=50, verbose_name='Действие')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Данные о том, что изменилось', verbose_name='Изменения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='booking.booking', verbose_name='Бронирование')),
                ('user', models.ForeignKey(blank=True, help_text='Кто выполнил действие', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История бронирования',
                'verbose_name_plural': 'История бронирований',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['booking', 'timestamp'], name='booking_boo_booking_6948a6_idx'), models.Index(fields=['action'], name='booking_boo_action_7823a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_phone', models.CharField(help_text='Номер телефона пользователя, которого приглашают', max_length=20, verbose_name='Телефон приглашённого')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, help_text='Дополнительное сообщение для приглашённого', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='booking.booking', verbose_name='Бронирование')),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Приглашённый пользователь')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Приглашение в бронирование',
                'verbose_name_plural': 'Приглашения в бронирования',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invitee', 'status'], name='booking_boo_invitee_637cc2_idx'), models.Index(fields=['booking', 'status'], name='booking_boo_booking_49bee7_idx'), models.Index(fields=['invitee_phone'], name='booking_boo_invitee_1cd3bd_idx'), models.Index(fields=['inviter', 'created_at'], name='booking_boo_inviter_2efa71_idx')],
                'unique_together': {('booking', 'invitee_phone')},
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['court', 'date', 'status'], name='booking_boo_court_i_3514ab_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='booking_boo_user_id_d9826d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'start_time'], name='booking_boo_date_804790_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['looking_for_partner', 'date'], name='booking_boo_looking_6e6ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'date'], name='booking_boo_user_id_6c0e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['coach', 'date'], name='booking_boo_coach_i_4d7410_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_type'], name='booking_boo_booking_149331_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_type', 'date'], name='booking_boo_booking_161c47_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='booking_pay_status_cb1e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='booking_pay_transac_be7684_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='booking_pay_created_3ae63b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status'], name='booking_pay_booking_b5375b_idx'),
        ),
    ]
