# Generated by Django 5.0.6 on 2026-01-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='required_rating_levels',
            field=models.JSONField(blank=True, default=list, help_text='Список буквенных рейтингов для поиска партнёров (например: ["C+", "B-", "B"])', verbose_name='Требуемые уровни игры'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='required_rating_level',
            field=models.CharField(blank=True, help_text='DEPRECATED: используйте required_rating_levels', max_length=10, null=True, verbose_name='Требуемый уровень игры (устаревшее)'),
        ),
    ]
